### ISSUE TITLE
Stack encountered errors while building package servant-pandoc-0.5.0.0 with ghc-9.8.4

### ISSUE THREAD

**Issue by ciukstar** [mpickering/servant-pandoc#15]
Stack encountered errors while building package `servant-pandoc-0.5.0.0` with `ghc-9.8.4`.

```
servant-pandoc> Configuring servant-pandoc-0.5.0.0...
servant-pandoc> build with ghc-9.8.4
servant-pandoc> Preprocessing library for servant-pandoc-0.5.0.0..
servant-pandoc> Building library for servant-pandoc-0.5.0.0..
servant-pandoc> [1 of 1] Compiling Servant.Docs.Pandoc
servant-pandoc> 
servant-pandoc> /tmp/stack-6cde3a88200a882c/servant-pandoc-0.5.0.0/src/Servant/Docs/Pandoc.hs:158:32: error: [GHC-83865]
servant-pandoc>     • Couldn't match type ‘(http-types-0.12.4:Network.HTTP.Types.Header.HeaderName,
servant-pandoc>                             bytestring-0.12.1.0:Data.ByteString.Internal.Type.ByteString)’
servant-pandoc>                      with ‘Text’
servant-pandoc>       Expected: Control.Lens.Getter.Getting [Text] Action [Text]
servant-pandoc>         Actual: ([http-types-0.12.4:Network.HTTP.Types.Header.Header]
servant-pandoc>                  -> Data.Functor.Const.Const
servant-pandoc>                       [Text] [http-types-0.12.4:Network.HTTP.Types.Header.Header])
servant-pandoc>                 -> Action -> Data.Functor.Const.Const [Text] Action
servant-pandoc>     • In the second argument of ‘(^.)’, namely ‘headers’
servant-pandoc>       In the first argument of ‘headersStr’, namely ‘(action ^. headers)’
servant-pandoc>       In the expression: headersStr (action ^. headers)
servant-pandoc>     |
servant-pandoc> 158 |       , headersStr  (action ^. headers)
servant-pandoc>     |                                ^^^^^^^
servant-pandoc> 
servant-pandoc> /tmp/stack-6cde3a88200a882c/servant-pandoc-0.5.0.0/src/Servant/Docs/Pandoc.hs:167:36: error: [GHC-83865]
servant-pandoc>     • Couldn't match type ‘[Char]’ with ‘Text’
servant-pandoc>       Expected: Text
servant-pandoc>         Actual: String
servant-pandoc>     • In the first argument of ‘B.code’, namely
servant-pandoc>         ‘(showPath (endpoint ^. path))’
servant-pandoc>       In the expression: B.code (showPath (endpoint ^. path))
servant-pandoc>       In the first argument of ‘mconcat’, namely
servant-pandoc>         ‘[B.str (convertString (endpoint ^. method)), B.space,
servant-pandoc>           B.code (showPath (endpoint ^. path))]’
servant-pandoc>     |
servant-pandoc> 167 |                          , B.code (showPath (endpoint ^. path))
servant-pandoc>     |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
servant-pandoc> 
```

**Comment by ciukstar** [comment]
Pull request #14 solves this issue. Please merge.
